Changing DNS resolver from google to OpenNIC
dappnode/DNP_BIND pull request #9
Opened 2018-10-21 10:36 UTC by albpal

This PR is related to the work done in https://gitcoin.co/issue/dappnode/DAppNode/31/1421

2018-10-24 11:13 UTC, vdo requested changes

2018-10-24 11:13 UTC, vdo commented on build/bind/eth.hosts
> +my.installer		A	172.33.1.7
Do you mind changing `installer` to `dappmanager` here?

2018-10-24 11:14 UTC, vdo commented on build/bind/named.conf
> +		169.239.202.202;
I think it would be nice to have a third resolver here just in case OpenNIC ones don't work

2018-10-24 11:25 UTC, albpal commented on build/bind/named.conf
> +		169.239.202.202;
The problem with this option is that if you add a resolver that doesn't resolve OpenNIC domains, you cannot guarantee that you will always resolve OpenNIC domains. Bind doesn't resolve in list order as /etc/resolv.conf does.

2018-11-05 03:14 UTC, vdo commented
Thanks @albpal . Your PR looks much better now. It will be merged once we test it.

2018-12-14 11:47 UTC, Shelpin commented
Hey @vdo !has this been tested implemented?? please let me know when it is done to include it in user doc...thanks!!!

2018-12-20 04:50 UTC, dapplion commented
Will review this in the next meeting

2019-01-17 10:43 UTC, Shelpin commented
Implemented DNScrypt...Thanks @albpal !!

2019-01-17 10:43 UTC, closed without merging